"""Add flagged entities tables

Revision ID: 53d1004a8013
Revises: 580419315288
Create Date: 2024-08-10 17:36:48.937137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d1004a8013'
down_revision = '580419315288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_influencer',
    sa.Column('FlagID', sa.Integer(), nullable=False),
    sa.Column('InfluencerID', sa.Integer(), nullable=False),
    sa.Column('FlagReason', sa.String(length=500), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['InfluencerID'], ['influencer.InfluencerID'], ),
    sa.PrimaryKeyConstraint('FlagID')
    )
    op.create_table('flagged_sponsor',
    sa.Column('FlagID', sa.Integer(), nullable=False),
    sa.Column('SponsorID', sa.Integer(), nullable=False),
    sa.Column('FlagReason', sa.String(length=500), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SponsorID'], ['sponsor.SponsorID'], ),
    sa.PrimaryKeyConstraint('FlagID')
    )
    op.create_table('flagged_campaign',
    sa.Column('FlagID', sa.Integer(), nullable=False),
    sa.Column('CampaignID', sa.Integer(), nullable=False),
    sa.Column('FlagReason', sa.String(length=500), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CampaignID'], ['campaign.CampaignID'], ),
    sa.PrimaryKeyConstraint('FlagID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_campaign')
    op.drop_table('flagged_sponsor')
    op.drop_table('flagged_influencer')
    # ### end Alembic commands ###
