"""Add CampaignID to Message model

Revision ID: 6dfcd2597dda
Revises: cebc9179bb94
Create Date: 2024-08-05 16:57:01.483803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfcd2597dda'
down_revision = 'cebc9179bb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CampaignID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        constraint_name='fk_message_campaign_id',  # This is the name for the foreign key constraint
        referent_table='campaign',
        local_cols=['CampaignID'],
        remote_cols=['CampaignID']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CampaignID')

    # ### end Alembic commands ###
